name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: |
          echo Hello World
          java -version
          javac -version
          
  calcadd:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calculator Add
        run: |
          javac *.java
          java -ea TestAdd
      
  calcsub:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calculator Subtract
        run: |
          javac *.java
          java -ea TestSub
